name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: say hello
      id: hello
      shell: bash
      run: |
        echo "Hello ${{ inputs.who }}"
