name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # checkout main branch
        with:
          fetch-depth: 0
          
      - name: say hello
        id: hello
        shell: bash
        run: |
          echo "Hello ${{ inputs.who }}"
          ls -l .github/workflows scripts

      - name: call build.sh
        id: call
        shell: bash
        run: |
          cat scripts//build.sh
